### ISSUE TITLE
Dependency on meteorhacks:flow-router

### ISSUE THREAD

**Issue by sergical** [PhilippSpo/momentum-flow-router#4]
Your package is adding `meteorhacks:flow-router` which results in a break since `kadira:flow-router` is the 2.0 version of Flow Router. Would you be able to change the dependencies to fix this?

**Comment by PhilippSpo** [comment]
Thanks for reporting! Already had it running locally but hadn't published to atmosphere yet. Should be fixed now.

**Comment by sergical** [comment]
so `meteor update` and should be good? :)

**Comment by PhilippSpo** [comment]
That should do it yes ;)

**Comment by sergical** [comment]
Awesome, thanks @PhilippSpo !

**Comment by PhilippSpo** [comment]
@416serg Glad I could help :)
