### ISSUE TITLE
Would anyone find this useful? [Define transitions from array]

### ISSUE THREAD

**Issue by KyleKing** [PhilippSpo/momentum-flow-router#5]
Awesome package and thanks for releasing it!

I wrote a function that I thought someone might find useful. I wanted a faster and more scalable way to create the Transitioner transition order. For my app everything is arranged spatially from left to right [i.e. page 1 is to the left of page 2]. I mirrored this arrangement in an array, such as ['Page 1', 'Page 2']. The function then generates an object to define transitions.

``` coffee
@TransitionOrder = (Pages) ->
  # init vars
  Transitions = {}
  LastPage = ''

  # Loop through array of named flow routes
  _.each Pages, (Page) ->
    if LastPage != ''
      # Create object for one direction of motion
      ForwardPageKey = LastPage + '->' + Page
      Transitions[ForwardPageKey] = 'right-to-left'
      # Then create the same concept in reverse
      ReversePageKey = Page + '->' + LastPage
      Transitions[ReversePageKey] = 'left-to-right'
    LastPage = Page

  # Set default value to fade
  Transitions['default'] = 'fade'

  # Return transitions to Transitioner.setTransitions
  Transitions

# Order from left to right and the above function will spit out necessary object
Transitioner.setTransitions TransitionOrder [
  'about'
  'map'
  'mechanicView'
  'AdminCompilation'
  'progress'
  'chartsAdmin'
  'RFIDlayout'
  'timeseries'
  'Profile'
]
```

What do you all think of this? Any advice/improvements? I might extend the function to also loop through and create transitions for pages not directly next to each other.

**Comment by PhilippSpo** [comment]
Thanks for your appreciation :)
I think this is a great idea and a great pattern that I will be using in one of my projects as well now, since the app is also arranged spatially from left to right. Thanks for posting this. Maybe we can find a way to integrate this to the package ;)

**Comment by KyleKing** [comment]
Awesome! I'll have some time next week and can play around and submit a PR
