### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by guilcorp** [PhilippSpo/momentum-flow-router#8]
Hi, 
I'm testing your nice package but it's not working for me.
I've the same experience as on your Meteor Pad, no routing problem but no animation.

Is it normal your Meteor Pad is not working or it's me?

Thanks for your help!

**Comment by PhilippSpo** [comment]
Sorry for getting back on you so late. Something is definitely broken.. I'll look into it.

**Comment by guilcorp** [comment]
No problem, Thanks!

**Comment by PhilippSpo** [comment]
Alright I fixed some dependencies. Should be back to normal now. The meteorpad also works again ;)

**Comment by guilcorp** [comment]
Yes it's working. Thanks!
