### ISSUE TITLE
FlowRouter group routes

### ISSUE THREAD

**Issue by eddieux** [PhilippSpo/momentum-flow-router#9]
Should this plugin work with FlowRouter group routes? I can't manage to get it working, not sure where I did wrong. Normal routes works beautifully.

**Comment by eddieux** [comment]
Ok it works. I was using a different layout for the route group and I suppose multiple layouts are not supported yet.

**Comment by PhilippSpo** [comment]
Yes multiple layouts are not supported yet sadly.
